spring:
  application:
    name: ekart

  datasource:
    url: jdbc:postgresql://localhost:5432/ekart_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  secret: 1234567890123456789012345678901234567890123456789012345678901234
  expiration: 86400000